name: multiple-event-workflow
on:
  push:
  issues:
    types: [opened]
  workflow_dispatch:
jobs:
  multiple-event-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo hello world
      - name: Step2
        run: |
          echo hello world
          echo github action
