name: pull-request-workflow
# 트리거
on:
  pull_request:
    # 오픈일 때만 트리거
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo hello world
      - name: Step2
        run: |
          echo hello world
          echo github action
