name: needs workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo hello world
      - name: Step2
        run: |
          echo hello world
          echo github action
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Step3
        run: echo hello job2
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step3
        run: |
          echo hello job3 but failed
          exit 1
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
      - name: Step3
        run: |
          echo hello job4 
          echo will job3 be executed?
